# kthcloud/30-ml-apps/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Kubeflow Pipelines (SeaweedFS as default S3 storage)
  - ../applications/pipeline/overlays # Pipeline definitions stored in the database
  # - ../applications/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user-k8s-native # Pipeline Definitions Stored as Kubernetes Resources

  # Katib
  - ../applications/katib/upstream/installs/katib-with-kubeflow

  # Central Dashboard
  - ../applications/centraldashboard/overlays/oauth2-proxy

  # Admission Webhook
  - ../applications/admission-webhook/upstream/overlays/cert-manager

  # Jupyter Web App
  - ../applications/jupyter/jupyter-web-app/upstream/overlays/istio

  # Notebook Controller
  - ../applications/jupyter/notebook-controller/upstream/overlays/kubeflow

  # Profiles + KFAM with PSS (Pod Security Standards)
  - ../applications/profiles/pss # TODO MUST BE UPSTREAMED

  # PVC Viewer
  - ../applications/pvcviewer-controller/upstream/base

  # Volumes Web App
  - ../applications/volumes-web-app/upstream/overlays/istio

  # Tensorboards Controller
  - ../applications/tensorboard/tensorboard-controller/upstream/overlays/kubeflow

  # Tensorboard Web App
  - ../applications/tensorboard/tensorboards-web-app/upstream/overlays/istio

  # Training Operator (v1)
  # - ../applications/training-operator/upstream/overlays/kubeflow
  # Trainer (Training Operator v2)
  - ../applications/trainer/overlays

  # Spark Operator
  # - ../applications/spark/spark-operator/overlays/kubeflow
