# kthcloud/20-kubeflow-core/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Base namespaces & policies
  - ../../common/kubeflow-namespace/base
  - ../../common/kubeflow-roles/base
  - ../../common/user-namespace/base

  - ../../applications/dashboard/overlays/istio
  - ../../applications/notebooks-v1/overlays/istio
